FROM ubuntu:20.04

LABEL maintainer="Taylor Otwell"

# Laravel Sail - last ubuntu:20.04 Sail build release 1.38.0 - https://github.com/laravel/sail/tree/v1.38.0
ARG WWWGROUP
ARG NODE_VERSION=20
ARG POSTGRES_VERSION=9.5

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
ENV SUPERVISOR_PHP_COMMAND="/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80"
ENV SUPERVISOR_PHP_USER="sail"

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom && \
    echo "Acquire::BrokenProxy    true;" >> /etc/apt/apt.conf.d/99custom

# php-7.0 support removed from offical ppa-ondrej - using cloned repo found at https://launchpad.net/ubuntu/+ppas?name_filter=ondrej
# # https://launchpad.net/~jason.grammenos.agility/+archive/ubuntu/php-static/+index?batch=75&direction=backwards&start=75

RUN apt-get update && apt-get upgrade -y \
    && mkdir -p /etc/apt/keyrings \
    && apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 dnsutils librsvg2-bin fswatch ffmpeg nano \
    && curl -sS 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c' | gpg --dearmor | tee /usr/share/keyrings/ppa_ondrej_php.gpg > /dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu focal main" > /etc/apt/sources.list.d/ppa_ondrej_php.list \
    && apt-get install -y software-properties-common vim httpie \
    && add-apt-repository ppa:jason.grammenos.agility/php-static \
    && apt-get update

# Add php 7.0 support
RUN apt install -y php7.0 php7.0-fpm \
    php7.0-pgsql php7.0-sqlite3 php7.0-redis \
    php7.0-intl php7.0-mbstring php7.0-json php7.0-yaml php7.0-gd php7.0-gmp php7.0-dom php7.0-imagick php7.0-sodium php7.0-mcrypt php7.0-zip php7.0-cli \
    php7.0-uuid php7.0-opcache php7.0-mysql php7.0-bz2 php7.0-ssh2 php7.0-xsl php7.0-xml php7.0-curl \
    php7.0-xdebug php7.0-imap \
    && curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer --2.2

# php7.0-memcached fails to install - install pre-build versions.
COPY memcached/memcached.so /usr/lib/php/20151012/memcached.so
COPY memcached/20-memcached.ini /etc/php/7.0/cli/conf.d/20-memcached.ini

RUN curl -sLS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer --2.2 \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" > /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs

#RUN npm install -g npm \
#    && npm install -g bun \

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn \
    && apt-get install -y mysql-client

COPY postgresql/postgresql-9.5.list  /etc/apt/sources.list.d/

# https://apt-archive.postgresql.org/pub/repos/apt/index.html
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8 \
  && apt update \
  && apt-get install -y postgresql-client-$POSTGRES_VERSION

## Add developer convenience tools
RUN apt install -y iputils-ping curl wget httpie traceroute gettext-base unzip zip git docutils-common htop

## Add support for puppeteer / chrome in testing
RUN apt install -y --no-install-recommends fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst \
    fonts-freefont-ttf libxss1 ca-certificates fonts-liberation libayatana-appindicator3-1 libasound2 \
    libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 \
    libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 \
    libx11-xcb1 libxshmfence-dev libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 \
    libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

RUN groupadd --force -g $WWWGROUP sail
RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1337 sail

# Load developer helper functions when starting interactive shell with www container
RUN echo 'source $HOME/bin/functions' >> /home/sail/.profile

COPY functions /home/sail/bin/
COPY start-container /usr/local/bin/start-container
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN apt-get install -y php7.0-dev git pkg-config build-essential libmemcached-dev
RUN npm install -g bin && npm install -g npm

RUN setcap "cap_net_bind_service=+ep" /usr/bin/php7.0
COPY php.ini /etc/php/7.0/cli/conf.d/99-sail.ini

RUN chmod +x /usr/local/bin/start-container

EXPOSE 80/tcp

ENTRYPOINT ["start-container"]
